[Merged]
LangXfm0017=SupportFiles\merged_jpn.mst
Path=SupportFiles\merged.cab

[Settings]
WelcomeAutoAdvance=0

[Dialogs]
Welcome=1
License=0
License2=1
UserInfo=0
FeatureInfo1=0
SingleDirectory=1
InstallationType=0
FeatureTree=1
HPVisa=1
FeatureInfo2=0
ConfirmStart=1
End=1

[Distribution]
TiTle=4
GUID={98EFA507-DC71-41BF-8D31-C9175648191E}
PackageGUID={88C9B3C8-0360-43E9-BB0E-E80B291BA3EB}
Version=16.0.0.30
IDPath=nidist.id
Has64bitPart=1

[SingleDirectoryDialog]
Dir1=NIDIR
DirText1=6;30,60,340,222

[Strings]
XXWelcomeTitle=4;20,40,320,100
WelcomeText=2;55,125,335,185
CopyrightText=5

[EndDialog]
Readme = 13;17,53,367,230;static

[Localization]
Languages=9,17
#ForceLanguage=9
StandardRes0017=SupportFiles\niresjpn.cab
CustomRes0017=SupportFiles\VisaInstallerJpnResDll.cab
CustomRes0009=SupportFiles\VisaInstallerEngResDll.cab
StandardLangXfm0007=SupportFiles\nistdtransbase.mst;SupportFiles\nistdtrans0007.mst
StandardLangXfm0012=SupportFiles\nistdtransbase.mst;SupportFiles\nistdtrans0012.mst
StandardLangXfm0017=SupportFiles\nistdtransbase.mst;SupportFiles\nistdtrans0017.mst
StandardLangXfm0018=SupportFiles\nistdtransbase.mst;SupportFiles\nistdtrans0018.mst
StandardLangXfm2052=SupportFiles\nistdtransbase.mst;SupportFiles\nistdtrans2052.mst

[Graphics]
TopBar=IDB_TOPSTRIP,IDB_TOPSTRIP,IDB_LARGETOPSTRIP,IDB_LARGETOPSTRIP
FullScreen=IDB_FULLSCREEN,IDB_FULLSCREEN,IDB_LARGEFULLSCREEN,IDB_LARGEFULLSCREEN

[InstallLevels]
Default=100

[MsiEngine]
WinNTPath=SupportFiles\WindowsInstaller-KB893803-v2-x86.exe
RequiredVersion=3.0.0.0
CommandLine=/passive /norestart

[Utilities]
UpgradeManagerPostProcessor=SupportFiles\nipie.exe
NISysInfo=SupportFiles\NISysInf.dll

[InitProgress]
left=55
top=200
right=270
bottom=210
red=255
green=255
blue=255
[OS]
VersionNTMin=6,1,7601,1,0
VersionNTMax=
[Parts]
EULADepot2.msi=
MDFSupport.msi=
MStudioCommonRuntime.v400.msi=
MStudioVISARuntime.v400.msi=
MStudioVISARuntime.v450.msi=
mxs.msi=
mxs64.msi=
MetaUninstaller.msi=
apalerri.msi=
apalerri64.msi=
dimSetup.msi=
dimSetup64.msi=
niorbi.msi=
niorbi64.msi=
palSetup.msi=
palSetup64.msi=
palerri.msi=
palerri64.msi=
niqpxi32.msi=
niqpxi64.msi=
nirocoerri32.msi=
nirocoerri64.msi=
rpcSetup.msi=
rpcSetup64.msi=
rpcSetupLVRT.msi=
NIVISADotNetRuntime.msi=
NIVISAHeaders.msi=
NIVISAHeaders64.msi=
NIVISAruntime.msi=
NIVISAruntime64.msi=
LegacyGPIBVXI.msi=
VisaSharedComponentsWrapper32.msi=
VisaSharedComponentsWrapper64.msi=
nimxRemoteServicei.msi=
nimxRemoteServicei64.msi=
NIER_Interface.msi=
NIER_Interface64.msi=
nisvcloc.msi=
nisysapi_x86.msi=
nisysapi_x64.msi=
signing.msi=
nicurl.msi=
nicurl64.msi=
nipxipferr32.msi=
nipxipferr64.msi=
ni_ssl.msi=
ni_ssl64.msi=
KillBit.msi=
KillBit64.msi=
VC2008MSMs_x86.msi=
VC2008MSMs_x64.msi=
VC2015Core.msi=
VC2015-32Wrapper.msi=
VC2015-64Wrapper.msi=
VisaNetSharedComponentsWrapperCore.msi=
VisaNetSharedComponentsWrapper32.msi=
VisaNetSharedComponentsWrapper64.msi=
nixerces27_win32.msi=
nixerces27_win64.msi=
mDNSResponder.msi=
mDNSResponder_W64.msi=
[EULADepot2.msi]
Path=Products\EULADepot\EULADepot2.msi
Volume=1
ProductCode={1B8AE714-65FA-4A36-8879-0C0CA66422A0}
ProductId={1B8AE714-65FA-4A36-8879-0C0CA66422A0}
[MDFSupport.msi]
Path=Products\MDF\MDF\MDFSupport.msi
Volume=1
ProductCode={7B27EBE4-BDD1-4048-86D4-D9CFBE7A1937}
ProductId={7B27EBE4-BDD1-4048-86D4-D9CFBE7A1937}
[MStudioCommonRuntime.v400.msi]
Path=Products\MStudioCommonRuntimev400\MStudioCommonRuntime.v400.msi
Volume=1
ProductCode={8FB91FB8-153E-4C6B-B71B-3D217A75D5F1}
ProductId={8FB91FB8-153E-4C6B-B71B-3D217A75D5F1}
[MStudioVISARuntime.v400.msi]
Path=Products\MStudioVisaNSRuntimev400\MStudioVISARuntime.v400.msi
Volume=1
ProductCode={C72F26AF-4266-4899-B4B6-626B100E3179}
ProductId={C72F26AF-4266-4899-B4B6-626B100E3179}
[MStudioVISARuntime.v450.msi]
Path=Products\MStudioVisaNSRuntimev450\MStudioVISARuntime.v450.msi
Volume=1
ProductCode={18940A7E-211C-4A6B-9832-48E023A55ACC}
ProductId={18940A7E-211C-4A6B-9832-48E023A55ACC}
[mxs.msi]
Path=Products\MXS\mxs.msi
Volume=1
ProductCode={EDE4907D-CD01-4D95-869B-BB96FFC9FF2B}
ProductId={EDE4907D-CD01-4D95-869B-BB96FFC9FF2B}
[mxs64.msi]
Path=Products\MXS\mxs64.msi
Volume=1
ProductCode={FDA65638-5522-4EE7-A407-61411B0C6549}
[MetaUninstaller.msi]
Path=Products\MetaUninstaller\MU\MetaUninstaller.msi
Volume=1
ProductCode={A41E5391-A6E7-40B8-9374-0E9E8B8B4CB7}
ProductId={A41E5391-A6E7-40B8-9374-0E9E8B8B4CB7}
[apalerri.msi]
Path=Products\NI-APAL_Error_Files\apalerri.msi
Volume=1
ProductCode={48E3422A-2764-4AC0-9027-D066001158C7}
ProductId={48E3422A-2764-4AC0-9027-D066001158C7}
[apalerri64.msi]
Path=Products\NI-APAL_Error_Files\apalerri64.msi
Volume=1
ProductCode={B9447E18-0E04-490E-8800-2412FE459A8B}
[dimSetup.msi]
Path=Products\NI-DIM\dimSetup.msi
Volume=1
ProductCode={7B34F0FB-C852-460E-BA4F-305AB0362212}
ProductId={7B34F0FB-C852-460E-BA4F-305AB0362212}
[dimSetup64.msi]
Path=Products\NI-DIM\dimSetup64.msi
Volume=1
ProductCode={236173D6-DE87-46DD-858E-3D43B4D1A033}
[niorbi.msi]
Path=Products\NI-ORB\niorbi.msi
Volume=1
ProductCode={DB97EB98-C805-4510-862C-FACF7C7F9917}
ProductId={DB97EB98-C805-4510-862C-FACF7C7F9917}
[niorbi64.msi]
Path=Products\NI-ORB\niorbi64.msi
Volume=1
ProductCode={4322ED67-A2E0-480C-B2F7-7C9CDD82B599}
[palSetup.msi]
Path=Products\NI-PAL\palSetup.msi
Volume=1
ProductCode={69C9F553-27CB-49B8-8081-699321DC08EB}
ProductId={69C9F553-27CB-49B8-8081-699321DC08EB}
LangXfm0007=Products\NI-PAL\palSetup_deu.mst
LangXfm0012=Products\NI-PAL\palSetup_fra.mst
LangXfm0017=Products\NI-PAL\palSetup_jpn.mst
LangXfm0018=Products\NI-PAL\palSetup_kor.mst
LangXfm2052=Products\NI-PAL\palSetup_chs.mst
[palSetup64.msi]
Path=Products\NI-PAL\palSetup64.msi
Volume=1
ProductCode={332DBB79-0F98-4939-BA8B-29A6A88BA46A}
LangXfm0007=Products\NI-PAL\palSetup64_deu.mst
LangXfm0012=Products\NI-PAL\palSetup64_fra.mst
LangXfm0017=Products\NI-PAL\palSetup64_jpn.mst
LangXfm0018=Products\NI-PAL\palSetup64_kor.mst
LangXfm2052=Products\NI-PAL\palSetup64_chs.mst
[palerri.msi]
Path=Products\NI-PAL_Error_Files\palerri.msi
Volume=1
ProductCode={1691794E-849D-439E-A0FF-D219981401E4}
ProductId={1691794E-849D-439E-A0FF-D219981401E4}
[palerri64.msi]
Path=Products\NI-PAL_Error_Files\palerri64.msi
Volume=1
ProductCode={876E98C3-90B2-45D0-821D-E7A9C990D46A}
[niqpxi32.msi]
Path=Products\NI-QPXI\niqpxi32.msi
Volume=1
ProductCode={C1812216-15C3-4A08-9547-D96340259541}
ProductId={C1812216-15C3-4A08-9547-D96340259541}
[niqpxi64.msi]
Path=Products\NI-QPXI\niqpxi64.msi
Volume=1
ProductCode={BA8EDFEE-C1B6-4EBE-8BA3-7517C238FF55}
[nirocoerri32.msi]
Path=Products\NI-ROCO_Error_Files\nirocoerri32.msi
Volume=1
ProductCode={7C7042C2-507F-4A22-AE36-422F57AD36B6}
ProductId={7C7042C2-507F-4A22-AE36-422F57AD36B6}
[nirocoerri64.msi]
Path=Products\NI-ROCO_Error_Files\nirocoerri64.msi
Volume=1
ProductCode={D5E21348-13C3-4B30-AC52-584D95D2DC5A}
[rpcSetup.msi]
Path=Products\NI-RPC\rpcSetup.msi
Volume=1
ProductCode={C1731602-D122-42AC-8DE5-FB31E7831B93}
ProductId={C1731602-D122-42AC-8DE5-FB31E7831B93}
[rpcSetup64.msi]
Path=Products\NI-RPC\rpcSetup64.msi
Volume=1
ProductCode={3DF614A4-1BD4-4801-AEBE-5D5A28829FA8}
[rpcSetupLVRT.msi]
Path=Products\NI-RPC_RT\rpcSetupLVRT.msi
Volume=1
ProductCode={047392F7-F447-4947-AD5C-D74E7F0F4AA9}
ProductId={047392F7-F447-4947-AD5C-D74E7F0F4AA9}
[NIVISADotNetRuntime.msi]
Path=Products\NI-VISA_DotNet_Runtime\NIVISADotNetRuntime.msi
Volume=1
ProductCode={25DEC6AC-4FED-4499-AD2F-BA922D96FBC5}
ProductId={25DEC6AC-4FED-4499-AD2F-BA922D96FBC5}
LangXfm0007=Products\NI-VISA_DotNet_Runtime\NIVISADotNetRuntime_deu.mst
LangXfm0012=Products\NI-VISA_DotNet_Runtime\NIVISADotNetRuntime_fra.mst
LangXfm0017=Products\NI-VISA_DotNet_Runtime\NIVISADotNetRuntime_jpn.mst
LangXfm0018=Products\NI-VISA_DotNet_Runtime\NIVISADotNetRuntime_kor.mst
LangXfm2052=Products\NI-VISA_DotNet_Runtime\NIVISADotNetRuntime_chs.mst
[NIVISAHeaders.msi]
Path=Products\NI-VISA_Headers\NIVISAHeaders.msi
Volume=1
ProductCode={4C188304-2F21-4B2E-8EC4-45507F030FEF}
ProductId={4C188304-2F21-4B2E-8EC4-45507F030FEF}
[NIVISAHeaders64.msi]
Path=Products\NI-VISA_Headers\NIVISAHeaders64.msi
Volume=1
ProductCode={F9B39497-C63A-40B9-A53C-EFA7BD813F80}
[NIVISAruntime.msi]
Path=Products\NI-VISA_Runtime\NIVISAruntime.msi
Volume=1
ProductCode={272BF3A9-7DBB-47EE-B2B8-CB893AA8166B}
ProductId={272BF3A9-7DBB-47EE-B2B8-CB893AA8166B}
PrimaryUpdateSource=1
LangXfm0007=Products\NI-VISA_Runtime\NIVISAruntime_deu.mst
LangXfm0012=Products\NI-VISA_Runtime\NIVISAruntime_fra.mst
LangXfm0017=Products\NI-VISA_Runtime\NIVISAruntime_jpn.mst
LangXfm0018=Products\NI-VISA_Runtime\NIVISAruntime_kor.mst
LangXfm2052=Products\NI-VISA_Runtime\NIVISAruntime_chs.mst
[NIVISAruntime64.msi]
Path=Products\NI-VISA_Runtime\NIVISAruntime64.msi
Volume=1
ProductCode={0EEB5487-1AEF-4C8A-A1E1-927039C1472F}
[LegacyGPIBVXI.msi]
Path=Products\NI-VISA_Runtime\LegacyGPIBVXI.msi
Volume=1
ProductCode={8CC4F89C-CEC8-455D-9213-F0B72E9BA192}
LangXfm0007=Products\NI-VISA_Runtime\LegacyGPIBVXI_deu.mst
LangXfm0012=Products\NI-VISA_Runtime\LegacyGPIBVXI_fra.mst
LangXfm0017=Products\NI-VISA_Runtime\LegacyGPIBVXI_jpn.mst
LangXfm0018=Products\NI-VISA_Runtime\LegacyGPIBVXI_kor.mst
LangXfm2052=Products\NI-VISA_Runtime\LegacyGPIBVXI_chs.mst
[VisaSharedComponentsWrapper32.msi]
Path=Products\NI-VISA_Runtime\VisaSharedComponentsWrapper32.msi
Volume=1
ProductCode={05C30C69-A9FD-4B55-8109-AA47C3212CBC}
[VisaSharedComponentsWrapper64.msi]
Path=Products\NI-VISA_Runtime\VisaSharedComponentsWrapper64.msi
Volume=1
ProductCode={F554427B-B649-41F3-96D7-CD3183E662E6}
[nimxRemoteServicei.msi]
Path=Products\NI-mx_Remote_Configuration\nimxRemoteServicei.msi
Volume=1
ProductCode={1943DAB5-9801-4C30-8003-358ED7DC47DA}
ProductId={1943DAB5-9801-4C30-8003-358ED7DC47DA}
[nimxRemoteServicei64.msi]
Path=Products\NI-mx_Remote_Configuration\nimxRemoteServicei64.msi
Volume=1
ProductCode={BFF116ED-35CA-4158-872E-1986E5131446}
[NIER_Interface.msi]
Path=Products\NIER_Interface\NIER_Interface.msi
Volume=1
ProductCode={A64EEEED-6B8D-4369-AEDB-A65ABC3D5C9C}
ProductId={A64EEEED-6B8D-4369-AEDB-A65ABC3D5C9C}
[NIER_Interface64.msi]
Path=Products\NIER_Interface\NIER_Interface64.msi
Volume=1
ProductCode={19723BE5-D757-4269-8128-65AA5235D14E}
[nisvcloc.msi]
Path=Products\NIServiceLocator\svcloc\nisvcloc.msi
Volume=1
ProductCode={0F816C63-EC59-4A1D-9657-536C0A48DA01}
ProductId={0F816C63-EC59-4A1D-9657-536C0A48DA01}
LangXfm0007=Products\NIServiceLocator\svcloc\svcloc_deu.mst
LangXfm0012=Products\NIServiceLocator\svcloc\svcloc_fra.mst
LangXfm0017=Products\NIServiceLocator\svcloc\svcloc_jpn.mst
LangXfm0018=Products\NIServiceLocator\svcloc\svcloc_kor.mst
LangXfm2052=Products\NIServiceLocator\svcloc\svcloc_chs.mst
[nisysapi_x86.msi]
Path=Products\NISysAPI_Framework\nisysapi_x86.msi
Volume=1
ProductCode={8FD3323C-9C4E-4CA9-BBC6-7EF554625DFE}
ProductId={8FD3323C-9C4E-4CA9-BBC6-7EF554625DFE}
[nisysapi_x64.msi]
Path=Products\NISysAPI_Framework\nisysapi_x64.msi
Volume=1
ProductCode={DAF5F16E-9A9B-42A4-8B17-FC0530BB1BA3}
[signing.msi]
Path=Products\NI_Certificates\signing.msi
Volume=1
ProductCode={AD9B4F25-F129-4B51-9C05-42F8BF9A5242}
ProductId={AD9B4F25-F129-4B51-9C05-42F8BF9A5242}
[nicurl.msi]
Path=Products\NI_Curl\nicurl.msi
Volume=1
ProductCode={CE9BC910-D93D-4083-93C7-0827EDAABC68}
ProductId={CE9BC910-D93D-4083-93C7-0827EDAABC68}
[nicurl64.msi]
Path=Products\NI_Curl\nicurl64.msi
Volume=1
ProductCode={99E6F61D-09DC-43B5-88CF-740FAD0D461D}
[nipxipferr32.msi]
Path=Products\NI_PXI_Platform_Framework_Error_Files\nipxipferr32.msi
Volume=1
ProductCode={B1179EA6-D139-42CF-81BE-CCE21E101A20}
ProductId={B1179EA6-D139-42CF-81BE-CCE21E101A20}
[nipxipferr64.msi]
Path=Products\NI_PXI_Platform_Framework_Error_Files\nipxipferr64.msi
Volume=1
ProductCode={3645FB1A-29A5-48EA-A073-874DA7E4A08A}
[ni_ssl.msi]
Path=Products\NI_SSL_Support\ni_ssl.msi
Volume=1
ProductCode={5E207DE6-086F-4548-9052-0DCCD3480C6A}
ProductId={5E207DE6-086F-4548-9052-0DCCD3480C6A}
LangXfm0007=Products\NI_SSL_Support\ssl_deu.mst
LangXfm0012=Products\NI_SSL_Support\ssl_fra.mst
LangXfm0017=Products\NI_SSL_Support\ssl_jpn.mst
LangXfm0018=Products\NI_SSL_Support\ssl_kor.mst
LangXfm2052=Products\NI_SSL_Support\ssl_chs.mst
[ni_ssl64.msi]
Path=Products\NI_SSL_Support\ni_ssl64.msi
Volume=1
ProductCode={B4BE40DC-5025-4F17-99EC-3DF401B8732F}
LangXfm0007=Products\NI_SSL_Support\ssl64_deu.mst
LangXfm0012=Products\NI_SSL_Support\ssl64_fra.mst
LangXfm0017=Products\NI_SSL_Support\ssl64_jpn.mst
LangXfm0018=Products\NI_SSL_Support\ssl64_kor.mst
LangXfm2052=Products\NI_SSL_Support\ssl64_chs.mst
[KillBit.msi]
Path=Products\SecurityUpdate_KB67L8LCQW_KillBit\KillBit.msi
Volume=1
ProductCode={20124E21-206B-485F-838F-14BB88161045}
ProductId={20124E21-206B-485F-838F-14BB88161045}
[KillBit64.msi]
Path=Products\SecurityUpdate_KB67L8LCQW_KillBit\KillBit64.msi
Volume=1
ProductCode={4A78D9E6-D349-4CCA-9295-45B12BE5BC6C}
[VC2008MSMs_x86.msi]
Path=Products\VC2008MSMs\VC2008MSMs\VC2008MSMs_x86.msi
Volume=1
ProductCode={E84997A1-4D6F-4C0B-B60D-F85B360D2666}
ProductId={E84997A1-4D6F-4C0B-B60D-F85B360D2666}
[VC2008MSMs_x64.msi]
Path=Products\VC2008MSMs\VC2008MSMs\VC2008MSMs_x64.msi
Volume=1
ProductCode={07E00E94-7A78-40FA-9BEF-71C190E98041}
[VC2015Core.msi]
Path=Products\VC2015_Runtime\VC2015\VC2015Core.msi
Volume=1
ProductCode={78E56459-2292-4BDF-876E-F4EF35298A5B}
ProductId={78E56459-2292-4BDF-876E-F4EF35298A5B}
LangXfm0007=Products\VC2015_Runtime\VC2015\VC2015Core_deu.mst
LangXfm0012=Products\VC2015_Runtime\VC2015\VC2015Core_fra.mst
LangXfm0017=Products\VC2015_Runtime\VC2015\VC2015Core_jpn.mst
LangXfm0018=Products\VC2015_Runtime\VC2015\VC2015Core_kor.mst
LangXfm2052=Products\VC2015_Runtime\VC2015\VC2015Core_chs.mst
[VC2015-32Wrapper.msi]
Path=Products\VC2015_Runtime\VC2015\VC2015-32Wrapper.msi
Volume=1
ProductCode={B10A37EF-AF49-48C0-93CC-D049681DE417}
[VC2015-64Wrapper.msi]
Path=Products\VC2015_Runtime\VC2015\VC2015-64Wrapper.msi
Volume=1
ProductCode={5B321CB9-9140-4E1D-AD80-C5E08B3E9754}
[VisaNetSharedComponentsWrapperCore.msi]
Path=Products\VISA_NET_Shared_Components\VisaNetSharedComponentsWrapperCore.msi
Volume=1
ProductCode={C0177533-A12F-4485-8DD6-D3ADAC7F13BD}
ProductId={C0177533-A12F-4485-8DD6-D3ADAC7F13BD}
[VisaNetSharedComponentsWrapper32.msi]
Path=Products\VISA_NET_Shared_Components\VisaNetSharedComponentsWrapper32.msi
Volume=1
ProductCode={AA33DE75-C4DA-4242-B619-E2E4D4503376}
[VisaNetSharedComponentsWrapper64.msi]
Path=Products\VISA_NET_Shared_Components\VisaNetSharedComponentsWrapper64.msi
Volume=1
ProductCode={64DA7319-86AB-414E-A35F-852DEEC965D9}
[nixerces27_win32.msi]
Path=Products\XercesDelayLoad27\nixerces27_win32.msi
Volume=1
ProductCode={AC2DBB64-C223-486B-88DB-95097232E1D6}
ProductId={AC2DBB64-C223-486B-88DB-95097232E1D6}
[nixerces27_win64.msi]
Path=Products\XercesDelayLoad27\nixerces27_win64.msi
Volume=1
ProductCode={9DF9CBF1-5724-4942-A959-377D9723F2A3}
[mDNSResponder.msi]
Path=Products\mDNS_Responder\mDNSResponder.msi
Volume=1
ProductCode={6CED5B26-5F59-4586-9EC0-3E92B5ECF76E}
ProductId={6CED5B26-5F59-4586-9EC0-3E92B5ECF76E}
[mDNSResponder_W64.msi]
Path=Products\mDNS_Responder\mDNSResponder_W64.msi
Volume=1
ProductCode={6E8CCE41-38E3-4815-8D9F-A8B502DACD41}
[Files]
License2TextFile0009=NI;license\NI Released License Agreement - English.rtf
License2TextFile0010=NI;license\NI Released License Agreement - Spanish.rtf
License2TextFile0016=NI;license\NI Released License Agreement - Italian.rtf
License2TextFile0007=NI;license\NI Released License Agreement - German.rtf
License2TextFile0012=NI;license\NI Released License Agreement - French.rtf
License2TextFile0017=NI;license\NI Released License Agreement - Japanese.rtf
License2TextFile0018=NI;license\NI Released License Agreement - Korean.rtf
License2TextFile2052=NI;license\NI Released License Agreement - Simplified Chinese.rtf
License3TextFile0009=IVI;license\IVI Foundation Inc License Agreement - English.rtf
[LicenseTypes]
LicenseType2=NIStandardReleased
LicenseType3=IVI
LicenseType4=Apache20
LicenseType5=Boost
LicenseType6=BSD3Clause
LicenseType7=CPOL
LicenseType8=LGPL
LicenseType9=md5mda
LicenseType10=MicrosoftLimitedPublicLicenseMSDN
LicenseType11=MicrosoftPlatformSDKServer2003SP1
LicenseType12=MicrosoftWindowsDriverKit
LicenseType13=MSVC 2015 Runtime
LicenseType14=MIT
LicenseType15=MIT-X
LicenseType16=Mozilla20
LicenseType17=NICTA
LicenseType18=OPCClassicCOM
LicenseType19=OpenSSL
LicenseType20=STLPort
LicenseType21=UPX
LicenseType22=wxWindows
[LicenseType2]
IsDisplayedAlone=0
IsThirdParty=0
IsHideInMetaSuite=0
[LicenseType3]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType4]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType5]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType6]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType7]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType8]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType9]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType10]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType11]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType12]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType13]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType14]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType15]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType16]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType17]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType18]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType19]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType20]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType21]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType22]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[PhoneHome]
DefaultState=1
Visible=1
LibPath=SupportFiles
[SilentInstallRequirements]
MustAcceptLicenses=1
